Travis: trying multiplatform test

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,34 +1,103 @@
-language: python
-python:
-  - "2.7"
-install:
-  - sudo apt-get update
-  - sudo apt-get install curl
-  # We do this conditionally because it saves us some downloading if the
-  # version is the same.
-  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
-      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
-    else
-      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
-    fi
-  - bash miniconda.sh -b -p $HOME/miniconda
-  - export PATH="$HOME/miniconda/bin:$PATH"
-  - hash -r
-  - conda config --set always_yes yes --set changeps1 no
-  - conda install -q conda-build
-  - conda update -q --all
-  # Useful for debugging any issues with conda
-  - conda info -a
+# Derived from https://github.com/theochem/qcgrids/blob/master/.travis.yml
+env:
+  matrix:
+  - MYCONDAPY=2.7
+  #- MYCONDAPY=3.5
+  #- MYCONDAPY=3.6
 
-  # Replace dep1 dep2 ... with your dependencies
-  - conda build -q conda-recipes/ucsf-chimera-headless
-  - conda create -q -n test-environment -c insilichem python=$TRAVIS_PYTHON_VERSION pytest
-  - source activate test-environment
-  - conda install -y -c $(conda info --root)/conda-bld ucsf-chimera-headless
-  # Headless installations produce a chimera-headless symlink
-  # that might not be catched by pychimera
-  - ln -s $CONDA_PREFIX/bin/chimera-headless $CONDA_PREFIX/bin/chimera
-  - python setup.py install
+####
+# EVERYTHING BELOW THIS LINE WILL BE COPIED INTO OTHER YMLs
+####
+
+# Do not use Travis Python to save some time.
+language: generic
+os:
+- linux
+- osx
+osx_image: xcode6.4
+dist: trusty
+sudo: false
+
+matrix:
+  # We only test on Linux with one specific Python version, unless we make a release. All
+  # other cases are allowed to fail and will exit early. With the fast_finish option,
+  # travis will send a status update to github as soon as the non-allowed-to-fail has
+  # finished. This speeds up testing in PRs.
+  #
+  # This is not ideal. It would be better to run just one item from the build matrix when
+  # not preparing a release. This is not possible on Travis. There are several tickets on
+  # travis-ci related to this limitation.
+  #
+  #    https://github.com/travis-ci/travis-ci/issues/7451
+  #    https://github.com/travis-ci/travis-ci/issues/7149
+  #    https://github.com/travis-ci/travis-ci/issues/2778
+  #    ...
+  fast_finish: true
+  allow_failures:
+  - os: osx
+
+cache:
+  directories:
+    - $HOME/download
+    - $HOME/miniconda
+
+before_cache:
+- if ! [[ $TRAVIS_TAG ]]; then rm -rf $HOME/miniconda/conda-bld; fi
+- rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history
+- pip uninstall -y pychimera
+
+branches:
+  only:
+    - master
+    - /^[0-9]+\.[0-9]+(\.[0-9]+)?([ab][0-9]+)?$/  # release branches
+
+before_install:
+- if ! [[ $TRAVIS_TAG || $TRAVIS_OS_NAME == "linux" && $MYCONDAPY == "2.7" ]]; then exit 0; fi
+# Get miniconda. Take the right version, so re-installing python is hopefully not needed.
+- if test -e $HOME/miniconda/bin; then
+    echo "miniconda already installed.";
+  else
+    echo "Installing miniconda.";
+    rm -rf $HOME/miniconda;
+    mkdir -p $HOME/download;
+    if [[ -d $HOME/download/miniconda.sh ]]; then rm -rf $HOME/download/miniconda.sh; fi;
+    if [ "${MYCONDAPY}" = "2.7" ]; then
+      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
+        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
+      else
+        wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh;
+      fi;
+    else
+      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
+        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
+      else
+        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh;
+      fi;
+    fi;
+    bash $HOME/download/miniconda.sh -b -p $HOME/miniconda;
+  fi
+
+
+install:
+- source $HOME/miniconda/bin/activate
+- hash -r
+
+# Configure conda and get a few essentials
+- conda config --set always_yes yes
+- conda install -q conda conda-build pytest
+# Show conda info for debugging
+- conda info -a
+
+# Check if UCSF Chimera is present and install it if needed
+- if [[ ! -e ~/.local/anaconda/bin/chimera ]]; then
+    conda build -q conda-recipes/ucsf-chimera-headless;
+    conda install -y -c $HOME/miniconda/conda-bld ucsf-chimera-headless;
+    # Headless installations produce a chimera-headless symlink
+    # that might not be catched by pychimera
+    ln -s $CONDA_PREFIX/bin/chimera-headless $CONDA_PREFIX/bin/chimera;
+  fi
+- python setup.py install
+
 
 script:
   - cd tests
